name: Combine and Zip Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up zip
      run: sudo apt-get install zip unzip -y

    - name: Unzip tweaks.zip
      run: unzip tweaks.zip -d tweaks

    - name: Copy repository files over tweaks files
      run: cp -r . tweaks/

    - name: Create pack.zip excluding tweaks.zip and extracted tweaks folder
      run: |
        cd tweaks
        zip -r ../pack.zip . -x "tweaks.zip" "tweaks/"

    - name: Commit and push pack.zip
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add pack.zip
        git commit -m 'Add generated pack.zip'
        git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:main
