name: Zip Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up zip
      run: sudo apt-get install zip -y

    - name: Create pack.zip excluding the existing pack.zip
      run: zip -r pack.zip . -x "pack.zip"

    - name: Commit and push pack.zip
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add pack.zip
        git commit -m 'Add generated pack.zip'
        git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:main
